CREATE TABLE "ca_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "ca_roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "tb_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" int NOT NULL,
  "title" int NOT NULL,
  "descritpion" varchar(200) NOT NULL,
  "level" varchar(15) NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "tb_courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int NOT NULL,
  "title" varchar(50) NOT NULL,
  "url" varchar(100) NOT NULL
);

CREATE TABLE "tb_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" int NOT NULL,
  "name" varchar(50) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(15) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "tb_users_courses" (
  "id_user" int NOT NULL,
  "id_course" int NOT NULL
);

CREATE TABLE "tb_teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

ALTER TABLE "tb_users" ADD FOREIGN KEY ("rol") REFERENCES "ca_roles" ("id");

ALTER TABLE "tb_users_courses" ADD FOREIGN KEY ("id_user") REFERENCES "tb_users" ("id");

ALTER TABLE "tb_users_courses" ADD FOREIGN KEY ("id_course") REFERENCES "tb_courses" ("id");

ALTER TABLE "tb_courses" ADD FOREIGN KEY ("category") REFERENCES "ca_categories" ("id");

ALTER TABLE "tb_courses" ADD FOREIGN KEY ("title") REFERENCES "tb_courses_video" ("id");

ALTER TABLE "tb_courses" ADD FOREIGN KEY ("teacher") REFERENCES "tb_teachers" ("id");

/*INDICACIONES*/

INSERT INTO tb_teachers (name) VALUES ('Andrés'), ('Ana');

INSERT INTO tb_courses_video (course, title, url) VALUES (1, 'Front End', 'frontend.com'), (2, 'Back End', 'backend.com');

INSERT INTO ca_categories (name) VALUES ('Node.js'), ('React');

INSERT INTO ca_roles (name) VALUES ('Student'), ('Teacher');

INSERT INTO tb_users (rol, name, email, password, age) VALUES (1, 'Pilar', 'pilar@gmail.com', 'pilarrr', 26), (2, 'Ana', 'ana@gmail.com', 'ana65', 30);

INSERT INTO tb_courses (category, title, descritpion, level, teacher) VALUES (1, 1, 'Fundamentos NODE', 'Medio', 1), (2, 2, 'Fundamentos React', 'Principiante', 2);

INSERT INTO tb_users_courses (id_user, id_course) VALUES (1, 1), (2, 2);

SELECT * FROM tb_users_courses JOIN tb_courses ON tb_courses.id=tb_users_courses.id_course;






